# Dockerfile best practices. [https://lipanski.com/posts/dockerfile-ruby-best-practices]
ARG RUBY_VERSION=3.0
FROM ruby:$RUBY_VERSION-alpine AS base

# Install system dependencies required both at runtime and build time.
#
# gcompat
#
#   LoadError: Error loading shared library ld-linux-aarch64.so.1: No such file or directory.
#   [https://nokogiri.org/tutorials/installing_nokogiri.html#linux-musl-error-loading-shared-library]
#   [https://wiki.alpinelinux.org/wiki/Running_glibc_programs]
#
# tmux
#
#   Used by overmind to connect to any process, which we'll use when debugging. [https://developers.forem.com/getting-started/start-app]
RUN apk update && apk add --no-cache --update postgresql-dev tzdata curl screen htop vim git bash yarn imagemagick gcompat tmux

# Match Gemfile.lock 'BUNDLED WITH' version.
ARG BUNDLER_VERSION=2.3
RUN gem install bundler:$BUNDLER_VERSION

# This stage is responsible for installing overmind in favour of foreman.
# [https://github.com/DarthSim/overmind#build-overmind-from-source]
# [https://github.com/DarthSim/overmind]
FROM base AS overmind
RUN apk add --no-cache --update go
RUN GO111MODULE=on go install github.com/DarthSim/overmind@v2

# This stage will be responsible for installing gems.
FROM base AS dependencies

# Install system dependencies required to build some Ruby gems (pg).
RUN apk add --update build-base

# Copying these files as an independent step, followed by bundle install, means that the project gems do not need to be rebuilt every time you make changes to
# your application code. This will work in conjunction with the gem_cache volumes that we will include in our docker-compose.yml file, which will mount gems to
# your application container in cases where the service is recreated but project gems remain the same.
COPY Gemfile Gemfile.lock ./
RUN bundle check || bundle install --jobs=2 --retry=3

# Runtime.
FROM base

# Create a non-root user to run the app and own app-specific files.
RUN adduser --disabled-password app

# Set the user for RUN, CMD or ENTRYPOINT calls from now on.
# Note that this doesn't apply to COPY or ADD, which use a --chown argument instead.
# Switch to this user.
USER app

# Set the base directory that will be used from now on.
# We'll install the app in this directory.
WORKDIR /home/app

# Copy over overmind from the overmind stage.
COPY --from=overmind /root/go/bin/overmind /usr/local/bin/

# Copy over gems from the dependencies stage.
COPY --from=dependencies /usr/local/bundle/ /usr/local/bundle/

# Finally, copy over the code.
COPY --chown=app . ./

# Script to be executed every time the container starts.
RUN chmod +x ./docker-entrypoint.sh
ENTRYPOINT ["./docker-entrypoint.sh"]

# Document which ports are intended to be published. This does not actually publish the port.
ENV PORT 3000
EXPOSE 3000

# Configure the main process to run when running the image.
CMD ["bin/rails", "server", "-b", "0.0.0.0"]
